### PR TITLE
Configurator: removed SystemContainer (BC break)

### PR DESCRIPTION
**Pull request by dg**
nette/di#10

### CODE REVIEW

**Comment by dg** [comment]
What do you think, merge it to 2.3?

**Comment by JanTvrdik** [comment]
What problem does it solve?

**Comment by dg** [comment]
You can easily create several containers (for testing), because class name is not always the same. 

Rather, my point is, if there is a reason to use name SystemContainer.

**Comment by JanTvrdik** [comment]
And will it be possible to always use `SystemContainer` if I want to?

**Comment by dg** [comment]
Hmmm, maybe it can be only disabled by default…

**Comment by fprochazka** [comment]
@dg I'm currently generating container names manually, to allow multiple different container instances at one runtime. If the containers names are trully unique to given set of config files and parameters, I have no problem with dropping support for custom naming.

**Comment by JanTvrdik** [comment]
I think we should certainly keep support for custom names but use random name by default.

**Comment by dg** [comment]
It generates always random names. Custom name is only emulated using PHP code:

```php
class CustomName extends Container_123RANDOM789 {}
```

**Pull request merged**
