### PR TITLE
Addeded method to register Nette\DI\Config\IAdapter

### PR DESCRIPTION
**Pull request by sallyx**
- feature
- BC break NO

### CODE REVIEW

**Comment by JanTvrdik** [comment]
I think that it is better to extend `Nette\Configurator` and override `createLoader` in your application. The use-case for this is IMHO too narrow.

**Comment by fprochazka** [comment]
@JanTvrdik which is problematic, if you wanna write an extension that adds xml adapter.

**Comment by dg** [comment]
addAdapter should be called in `onCompile` and it is imho late for adding new loaders.

**Comment by sallyx** [comment]
So, what is the result? Should I extend Nette\Configurator and relay on protected method not to be changed/removed in the future?

**Comment by f3l1x** [comment]
Any progress @sallyx? What should we do with this PR? @TomasVotruba @dg @JanTvrdik

**Comment by sallyx** [comment]
I have no idea. You should accept it or refuse it.

**Comment by TomasVotruba** [comment]
I don't get the feature and use case. Could you elaborate on small example?

**Comment by dg** [comment]
This should be solved this way https://github.com/nette/bootstrap/pull/39#issuecomment-121298933, closing.

**Pull request closed without merging**
